language: node_js
node_js:
- node
script:
- bin/update
after_success:
- ".travis/push.sh"
env:
  global:
    secure: i5UwfngyA2gnyB7FbQSNfC8eYFjNw6QRx20ZxxlkVivvoVThXSc2VGfBKNMelsSOWowd3Vufmrg4R4IkMzMwnLq6ThPwXaMV+BzYbMPgHNoQYnIjaVFOfif+HjLBmoZfZQNwmJF9CrlecS1jCxOFGtz2pJmixoSKuijlxZGyc5tYgAa+ZQlLTj4Lnohn/tnv62ydrdoqGRXKRBvFe7H8hDJPCRHk5tUuUfchabXTaDFfk6asFyW4OzjQ7LoHuKJlrx86bzIR8cY9p2+TE7BO+qHL7i/tkkUiadRFfqasUM1vV4U63m9BxTUwNiTdkSyXSCJlP7M9iR8KF5ockV8DFGAosoWEIQnY/7BaGbAhVJwkH+bSBTv73O8dj/R8pBfyHtdStHqxJJOLdpyIe60+xtRJsVmBY3JfoTaGxRulUbABIMUbEuEYgzjY7bB8IEossVq0V7hpQXnHHqBQGQBxc0xF5+1Z2JnaP3L2U7Fq2REGf+9UdASzZWVfZYi8hUWeNKA491oGwjgPSzhmprWbiRxQT9HRqOpvUWx1Xyy5qkyZZK8fh9Q3UHecnpWvq0HxVQ3SB0GOS4J5WTOBdszQYKFjcAnezx/jFPkanU0HenmtDblisMwO75tlG2SMSXX0k4IEb66qKs4wCZg2g16wnwcWCgdgBAPXf99Mtnm1PII=
